### ISSUE TITLE
Just copied my code 

### ISSUE THREAD

**Issue by clientlessx** [suegdu/Discord-Username-Checker#11]
You basically just re-wrote my code? And then tried to promote it on my discord server? you good

**Comment by suegdu** [comment]
my man, first of all i did not copy your code. I did not copy a single line of your code as you can see it all by yourself. Second, i did not "promote it" on your Discord server. I have been putting too much work on this project so you better check before you call someone "re-wrote my code". If you are talking about the Discord endpoint URL, then that's not "re-writing" there are a plenty of checkers that uses this endpoint as it is the only way to pass it through. Don't be mad over something because it may just fit the better than you what did.

**Comment by clientlessx** [comment]
Funny that the naming conventions like your naming of variables like "endpoint" code is so similar why didnt you name it "api" or something like that?

```py
       if json_endpoint.get("taken") is not None:
           if json_endpoint["taken"] is False:
            print(f"{Lb}[+]{Fore.LIGHTGREEN_EX} '{username}' available.")
            save(username)
            available_usernames.append(username)
           elif json_endpoint["taken"] is True:
              print(f"{Lb}[-]{Fore.RED} '{username}' taken.")
       else:
           print(f"{Lb}[?]{Fore.RED} Error validating '{username}': {endpoint.json()['message']} |DSV: Make sure you have a valid token.")
```

My code:
![image](https://github.com/suegdu/Discord-Username-Checker/assets/112898008/090f40ac-3c02-4d0f-9f1b-2858fd206455)

**Comment by suegdu** [comment]
Lmfao you literally copied that part of "is available" from me and you start calling me that i copied yours? read all what i said before you start crying here buddy also the part of "Endpoint json" again, as i mentioned before there are over 30 repos with the same-most code so open your eyes and read what i say before you start crying in here the whole endpoint thing is everywhere and i could use it anywhere because you did not made it it's absolutely what it's says the endpoint of Discord. Again read what i say.

**Comment by suegdu** [comment]
So you are here crying over 2 lines of code that everyone uses and saying "Hey you copied it from me" like what the hell are you expecting me to do lol once i see you cry on everyone's repo then we may have a little talk.
